pipeline {
    agent any
    stages {
        stage('Test') {
            agent {
                docker { image 'maven:3.9.6-eclipse-temurin-21' }
            }
            steps {
                dir('app-java-maven') {
                    sh '''
                    ./mvnw test
                    '''
                }
            }
        }
        stage('Docker Build') {
            steps {
                echo 'Construyendo imagen Docker...'
                dir('app-java-maven') {
                    sh "docker build -t localhost:5000/app-java-maven:\$(git rev-parse --short HEAD) ."
                    sh "docker push localhost:5000/app-java-maven:\$(git rev-parse --short HEAD)"
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Desplegando en el clúster de Kubernetes...'
                sh '''
                    kubectl apply -f k8s/dev/app-java-maven-deployment.yaml
                    kubectl set image deployment/app-java-maven app-java-maven=local-registry:5000/app-java-maven:$(git rev-parse --short HEAD) -n dev
                '''
            }
        }
    }
}
