pipeline {
    agent any
    stages {
        stage('Test') {
            agent {
                docker { image 'gradle:jdk21-alpine' }
            }
            steps {
                dir('app-java-gradle') {
                    sh '''
                    ./gradlew --no-daemon test
                    '''
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Desplegando en el clúster de Kubernetes...'
                sh 'kubectl apply -f k8s/dev/app-java-gradle-deployment.yaml'
            }
        }
    }
}
